gubernator-io/gubernator

- Dockerfile
- cmd/gubernator/main.go
- cmd/gubernator/main_test.go
Previous version broke the ability to start gubernator without a config file.
* Added a test for running gubernator from the CLI
* Added LABEL to image to tie image to the github repo
* Added exception to flag parser for `flag provided but not defined` as we need to pass additional flags in during a test
* `tracerCloser` is now closed when `Main()` returns
This should fix #3
> Fixed regression, gubernator should start without a config file

- config.go
- docker-compose-tls.yaml
- memberlist.go
This commit adds configuration fields to enable gossip encryption of memberlist. Without encryption, a malicious actor is able to add and remove members from the pool and cause general disruption to the service. Enabling encryption also acts as a pseudo-checksum and helps to ensure that no malformed UDP packets are accepted as valid messages.
> Add memberlist gossip encryption.

- cmd/gubernator/main.go
Hi, Currently the master branch and `ghcr.io/gubernator-io/gubernator:v2.7.1` image tag won't run with following error. 
```
INFO[0000] Gubernator dev-build (arm64/darwin)
FATA[0000] during tracing.NewResource()                  category=gubernator error="error in resource.Merge on resources index 0: conflicting Schema URL: https://opentelemetry.io/schemas/1.24.0 and https://opentelemetry.io/schemas/1.21.0"
exit status 1
```
I feel like this is similar to this commit:
https://github.com/gubernator-io/gubernator/commit/fc29185c2a58da152c85e13fcd8bb57d89f09049
> fix: Bump Otel semconv version to avoid error in tracing.NewResource()

- functional_test.go
- gubernator.go
Fixes #14
* The `err` returned by the call to `req.Peer.GetPeerRateLimit()` shadows the local `err` which is why the `err` is nil when the max number of attempts are reached.
* Fixed flapping test `TestLeakyBucketGregorian`
> Fixed possible nil err in asyncRequest

- config.go
`TraceLevelInfoFilter` isn't used - its only use was in https://github.com/gubernator-io/gubernator/blob/e054be398e78e5daad7a3d60e9045f8991f1f8d4/daemon.go#L116 but is currently commented.
This PR unblocks consumers of gubernator who also use the latest OTel libraries (version 0.52), as the type `otelgrpc.Filter` changed in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5196 ). See change [here](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5196/files#diff-2ae5aad56db1358284b4f15a611995b358dd898126b55c3a66ce254fa58c641eR30). The code I commented is now invalid with latest versions of OTel, which prevents consumers of OTel libraries to upgrade them if they also use gubernator. Building gubernator with the latest OTel libraries fails with:
``` …
```
> Comment TraceLevelInfoFilter as it breaks OTel compatibility

- Dockerfile
- README.md
- cmd/gubernator/main_test.go
- cmd/healthcheck/main.go
- config.go
- config_test.go
- contrib/aws-ecs-service-discovery-deployment/ecs_gubernator.tf
- contrib/aws-ecs-service-discovery-deployment/main.tf
- contrib/charts/gubernator/templates/_helpers.tpl
- contrib/charts/gubernator/values.yaml
- contrib/k8s-deployment.yaml
- dns.go
- docker-compose-tls.yaml
- docker-compose.yaml
- example.conf
Issue: https://github.com/gubernator-io/gubernator/issues/27
This adds a non root user to the Dockerfile that by default assumes the root user.
You can test it works locally like this:
<details>
<summary>Use this K8s manifest.</summary>
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: gubernator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: get-endpoints
rules:
- apiGroups:
- ""
resources:
- endpoints
verbs:
- list
- watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: get-endpoints
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: get-endpoints
subjects:
- kind: ServiceAccount
name: gubernator
---
apiVersion: v1
kind: Pod
metadata:
name: gubernator
labels:
app: gubernator
spec:
securityContext: …
```
> Running as a non root user

- .github/workflows/lint.yaml
- .github/workflows/on-pull-request.yml
- Makefile
- cluster/cluster.go
- cmd/gubernator-cli/main.go
- config.go
- daemon.go
- functional_test.go
- gubernator.go
This PR implements a generalized hook into rate limit hits by providing a unidirectional channel to receive request/response data.  The initial use case is to implement Prometheus metrics to monitor status of high value rate limit name/key pairs.
The user will populate `Config.EventChannel` with a channel and implement goroutine(s) to read from the channel.  An event is triggered when a rate limit hit is applied at its owner peer and request/response structures are sent to the channel.
This is intended to work for all peering behaviors: batching, non-batching, and global.
Other auxiliary changes:
- Upgrade `golangci-lint` to latest.
- Update GitHub Actions in workflows.
- Remove redundant call to `golangci-lint` in `on-pull-request` workflow.
- `cluster.StartWith()` extended with options …
> Add hook to `GetRateLimit`

- cluster/cluster.go
- cmd/gubernator-cli/main.go
- cmd/gubernator-cluster/main.go
- cmd/gubernator/main.go
- cmd/gubernator/main_test.go
- config.go
- config_test.go
- daemon.go
- dns.go
- etcd.go
- flags.go
- global.go
- go.mod
- gubernator.go
- kubernetes.go
- log.go
- logging.go
- memberlist.go
- peer.go
- tls.go
- tls_test.go
A possibly incomplete attempt to migrate the logging over to the now standard Go `slog` system.
I see one of the dependencies (holster) still using logrus, though...
> Attempt to switch logging to Go standard slog SDK logging

- example.conf
- tls.go
- tls_test.go
As I deploy gubernator with tls and need to rotate the cert/key, which are generated by some secret management tool like vault, I want the gubernator instance to reload the cert/key without being restarted.
This PR allows gubernator to hot-reload tls cert/key on receiving a `SIGHUP` signal. A `KeypairReloader` method is used to reload the cert/key and assigned to `GetCertificate`. 
Note that `clientTLS` is still statically assigned because `GetCertificate` is inapplicable to TLS client.
`example.conf` is updated.
> daemon: hot reload tls config

- gubernator.go
- peer_client.go
- workers.go
Calling `PeerClient.Shutdown()`, `V1Instance.Close()` or `WorkerPool.Close()` twice should be allowed. If the caller does call these methods twice, the methods will simply return `nil` with no further action taken.
Fixes #35
> Avoid calling Close() or Shutdown() more than once

- config.go
- config_test.go
As a user wants to use the V1Instance config,  we need `instanceID` in the logger field. This PR defaults the `instanceID` in the `SetDefaults` of the V1Instance.
> Fix: add missing default to the instanceID in Config

- config.go
- example.conf
- memberlist.go
As we deploy gubernator on a host where port `7946` has been take, we need to configure the memberlist using a different port than `7946`.
This PR introduce a new env var `GUBER_MEMBERLIST_BIND_ADDRESS` to allow configuring the `bindPort` and `bindAddr` of memberlist.
> Memberlist bind port

- example.conf
- tls.go
- tls_test.go
This PR fixes a bug in reloading the tls certificate for the gRPC client. Gubernator instance reports messages `remote error: tls: expired certificate` after running for a couple of days. 
in the current implementation, the client certificate of the key reload refers to a slice of `tls.Certificate` struct. During reload, there could be a chance the certificate is not loaded correctly, leading to the tls expiration error.
We use the `tls.GetClientCertificates` callback function to load the certificate for gRPC client to avoid any race condition. Additional improvements are that hot-reload of client cert is supported as well in this PR.
We deployed an image with the fix in 3-node cluster and let it run for 5 days with tls `ttl=5m`. There has been no error of tls expiration.
> [Bug fix] tls reload: enable for client cert

- config.go
- daemon.go
- example.conf
As we are using an in-house service discovery mechanism, we need to set the `GUBER_DISCOVERY_TYPE`  to something other than the existing [list](https://github.com/gubernator-io/gubernator/blob/22853694a31ba67c86a0598c90e3a8c76501a868/config.go#L340).
This PR adds a new discovery type named `embedded`  such thatit allows us to embed gubernator and manually call the method `daemon.SetPeers` to set the gubernator peers. I understood that we can bypass the configuration check by manually creating `DaemonConfig` . However, using the `SetupDaemonConfig`  is much easier and has proven to work for most settings. 
Therefore, with this PR, users can easily embed gubernator and manually set the peers.
> Config: add a new no-op discovery type

- cluster/cluster.go
- daemon.go
Based on the definition of `AdvertiseAddress` and `GRPCListenAddress`, I think here we should use `AdvertiseAddress`, which is default to `GRPCListenAddress`. However, if node is behind a NAT, we need to set `AdvertiseAddress` to a different value than `GRPCListenAddress`.
> daemon: fix condition to determin isOwner

- gubernator.go
The current implementation mistakes the error message for `sep`.
> Fix concatenated error message in healthCheck method

- .github/workflows/e2e.yml
- .golangci.yml
- cmd/healthcheck/main.go
- Add an action that runs Gubernator in Kubernetes, and validates that it is healthy.
- Modify healthcheck command to optionally support retries (for use in this test).
- It correctly shows that the latest Gubernator release is broken on Kubernetes.
- Hoepfully this will also let you progress with Gubernator v3, as you'll have a safety net.
```
checking "http://localhost:1050/v1/HealthCheck": attempt=54
checking "http://localhost:1050/v1/HealthCheck": attempt=55
checking "http://localhost:1050/v1/HealthCheck": attempt=56
checking "http://localhost:1050/v1/HealthCheck": attempt=57
checking "http://localhost:1050/v1/HealthCheck": attempt=58
checking "http://localhost:1050/v1/HealthCheck": attempt=59
checking "http://localhost:1050/v1/HealthCheck": attempt=60
on attempt '60'; attempts …
```
> Add GitHub action for testing k8s deployment

- contrib/charts/gubernator/templates/_helpers.tpl
- contrib/charts/gubernator/templates/deployment.yaml
Fixing helm deploy name, let you change the name of the deployment. It was static gubernator and now let us change this name as us like.
> fixing helm deploy name, max age connections and add support to a affinity and tolerations

- contrib/charts/gubernator/templates/_helpers.tpl
- contrib/charts/gubernator/templates/deployment.yaml
- contrib/charts/gubernator/templates/hpa.yaml
- contrib/charts/gubernator/templates/keda.yaml
- contrib/charts/gubernator/values.yaml
This update introduces support for KEDA (Kubernetes Event-driven Autoscaling) objects, enhancing the application's scalability capabilities. Additionally, the deployment configuration has been modified to allow for customizable naming conventions, providing greater flexibility in resource management. Lastly, the liveness and readiness probes have been removed from the deployment, simplifying the health check mechanism for the application.
> add support keda object, fix deployment to support different name and remove liveness and readiness probe

- peer_client.go
The optional log field did not had nil check into runBatch() function, added the nil check.
> Fix: handle nil log in sendBatch()

- contrib/charts/gubernator/templates/_helpers.tpl
The `app` label can be different if the helm release name is different than just `gubernator`. If hardcoded, the release won't find any peers, but we can just pull the value of the correct app label from the helm context.
> Ensure the endpoint selector references the helm app label

- config.go
- daemon.go
- example.conf
Kubernetes does not immediately remove a terminating Pod from the associated Service endpoints. This can result in in-flight requests being routed to a Pod that is already shutting down, potentially causing failed requests or degraded performance.
This change introduces a new configuration option: GracefulTerminationDelaySeconds. When set, the Daemon will sleep for the specified duration before beginning its shutdown sequence. This gives the Kubernetes endpoint controller time to update the endpoints list and stop directing traffic to the terminating Pod.
This delay improves the reliability of request handling during rolling updates, Pod evictions, and other lifecycle events, especially in latency-sensitive or stateful services.
> feat: Add Graceful Termination Delay
